//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PlantUMLGrammer.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPlantUMLGrammerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class PlantUMLGrammerBaseListener : IPlantUMLGrammerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] PlantUMLGrammerParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] PlantUMLGrammerParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.namespace_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_def([NotNull] PlantUMLGrammerParser.Namespace_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.namespace_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_def([NotNull] PlantUMLGrammerParser.Namespace_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.type_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_definition([NotNull] PlantUMLGrammerParser.Type_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.type_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_definition([NotNull] PlantUMLGrammerParser.Type_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.class_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_def([NotNull] PlantUMLGrammerParser.Class_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.class_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_def([NotNull] PlantUMLGrammerParser.Class_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.abstractclass_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbstractclass_def([NotNull] PlantUMLGrammerParser.Abstractclass_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.abstractclass_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbstractclass_def([NotNull] PlantUMLGrammerParser.Abstractclass_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.interface_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface_def([NotNull] PlantUMLGrammerParser.Interface_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.interface_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface_def([NotNull] PlantUMLGrammerParser.Interface_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColor([NotNull] PlantUMLGrammerParser.ColorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColor([NotNull] PlantUMLGrammerParser.ColorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.extrafield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtrafield([NotNull] PlantUMLGrammerParser.ExtrafieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.extrafield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtrafield([NotNull] PlantUMLGrammerParser.ExtrafieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation([NotNull] PlantUMLGrammerParser.RelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation([NotNull] PlantUMLGrammerParser.RelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirection([NotNull] PlantUMLGrammerParser.DirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirection([NotNull] PlantUMLGrammerParser.DirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.from"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrom([NotNull] PlantUMLGrammerParser.FromContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.from"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrom([NotNull] PlantUMLGrammerParser.FromContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.to"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTo([NotNull] PlantUMLGrammerParser.ToContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.to"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTo([NotNull] PlantUMLGrammerParser.ToContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.interface_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface_name([NotNull] PlantUMLGrammerParser.Interface_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.interface_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface_name([NotNull] PlantUMLGrammerParser.Interface_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.linktext"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinktext([NotNull] PlantUMLGrammerParser.LinktextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.linktext"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinktext([NotNull] PlantUMLGrammerParser.LinktextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.relationType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationType([NotNull] PlantUMLGrammerParser.RelationTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.relationType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationType([NotNull] PlantUMLGrammerParser.RelationTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.accessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessor([NotNull] PlantUMLGrammerParser.AccessorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.accessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessor([NotNull] PlantUMLGrammerParser.AccessorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldName([NotNull] PlantUMLGrammerParser.FieldNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldName([NotNull] PlantUMLGrammerParser.FieldNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.ownerClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwnerClass([NotNull] PlantUMLGrammerParser.OwnerClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.ownerClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwnerClass([NotNull] PlantUMLGrammerParser.OwnerClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.fieldType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldType([NotNull] PlantUMLGrammerParser.FieldTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.fieldType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldType([NotNull] PlantUMLGrammerParser.FieldTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.class_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_name([NotNull] PlantUMLGrammerParser.Class_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.class_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_name([NotNull] PlantUMLGrammerParser.Class_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.namespace_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_name([NotNull] PlantUMLGrammerParser.Namespace_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.namespace_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_name([NotNull] PlantUMLGrammerParser.Namespace_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] PlantUMLGrammerParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] PlantUMLGrammerParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.dotIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotIdentifier([NotNull] PlantUMLGrammerParser.DotIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.dotIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotIdentifier([NotNull] PlantUMLGrammerParser.DotIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.note_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNote_expr([NotNull] PlantUMLGrammerParser.Note_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.note_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNote_expr([NotNull] PlantUMLGrammerParser.Note_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.somethingsToEndNote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSomethingsToEndNote([NotNull] PlantUMLGrammerParser.SomethingsToEndNoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.somethingsToEndNote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSomethingsToEndNote([NotNull] PlantUMLGrammerParser.SomethingsToEndNoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlantUMLGrammerParser.somethings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSomethings([NotNull] PlantUMLGrammerParser.SomethingsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlantUMLGrammerParser.somethings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSomethings([NotNull] PlantUMLGrammerParser.SomethingsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
