//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PlantUMLGrammer.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public partial class PlantUMLGrammerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, NAMESPACE=23, CLASS=24, 
		ENUM=25, ABSTRACT=26, INTERFACE=27, COLON=28, STRING=29, SIGN=30, NUMBER=31, 
		STARTUML=32, ENDUML=33, AQOLADBAZ=34, AQOLADBASTE=35, SPACE=36, NewLine=37, 
		NOTE=38, Identifier=39, ENDNOTE=40, Unicode=41, Color=42;
	public const int
		RULE_file = 0, RULE_namespace_def = 1, RULE_type_definition = 2, RULE_enum_def = 3, 
		RULE_field_def_block = 4, RULE_field_def = 5, RULE_method_field = 6, RULE_class_def = 7, 
		RULE_streotype_def = 8, RULE_streotypename = 9, RULE_singleline_comment = 10, 
		RULE_rest_of_line = 11, RULE_abstractclass_def = 12, RULE_interface_def = 13, 
		RULE_color = 14, RULE_extrafield = 15, RULE_relation = 16, RULE_direction = 17, 
		RULE_from = 18, RULE_to = 19, RULE_interface_name = 20, RULE_linktext = 21, 
		RULE_relationType = 22, RULE_accessor = 23, RULE_fieldName = 24, RULE_ownerClass = 25, 
		RULE_fieldType = 26, RULE_class_name = 27, RULE_enum_name = 28, RULE_namespace_name = 29, 
		RULE_identifier = 30, RULE_dotIdentifier = 31, RULE_note_expr = 32, RULE_somethingsToEndNote = 33, 
		RULE_somethings = 34;
	public static readonly string[] ruleNames = {
		"file", "namespace_def", "type_definition", "enum_def", "field_def_block", 
		"field_def", "method_field", "class_def", "streotype_def", "streotypename", 
		"singleline_comment", "rest_of_line", "abstractclass_def", "interface_def", 
		"color", "extrafield", "relation", "direction", "from", "to", "interface_name", 
		"linktext", "relationType", "accessor", "fieldName", "ownerClass", "fieldType", 
		"class_name", "enum_name", "namespace_name", "identifier", "dotIdentifier", 
		"note_expr", "somethingsToEndNote", "somethings"
	};

	private static readonly string[] _LiteralNames = {
		null, "'{method}'", "'{field}'", "'<<'", "'>>'", "'''", "'#'", "'('", 
		"')'", "'<'", "'>'", "'--|>'", "'--'", "'<|--'", "'-->'", "'<--'", "'*--'", 
		"'*-'", "'-'", "'+'", "'~'", "'\"'", "'.'", null, "'class'", "'enum'", 
		"'abstract'", "'interface'", "':'", null, null, null, "'@startuml'", "'@enduml'", 
		"'{'", "'}'", null, null, "'note'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, "NAMESPACE", 
		"CLASS", "ENUM", "ABSTRACT", "INTERFACE", "COLON", "STRING", "SIGN", "NUMBER", 
		"STARTUML", "ENDUML", "AQOLADBAZ", "AQOLADBASTE", "SPACE", "NewLine", 
		"NOTE", "Identifier", "ENDNOTE", "Unicode", "Color"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlantUMLGrammer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlantUMLGrammerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PlantUMLGrammerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PlantUMLGrammerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STARTUML() { return GetToken(PlantUMLGrammerParser.STARTUML, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDUML() { return GetToken(PlantUMLGrammerParser.ENDUML, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(PlantUMLGrammerParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_definitionContext[] type_definition() {
			return GetRuleContexts<Type_definitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_definitionContext type_definition(int i) {
			return GetRuleContext<Type_definitionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE() { return GetToken(PlantUMLGrammerParser.SPACE, 0); }
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterFile(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitFile(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 0, RULE_file);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(STARTUML);
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 825432735776L) != 0) {
				{
				{
				State = 71;
				type_definition();
				}
				}
				State = 76;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 78;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPACE) {
				{
				State = 77;
				Match(SPACE);
				}
			}

			State = 80;
			Match(ENDUML);
			State = 81;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Namespace_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAMESPACE() { return GetToken(PlantUMLGrammerParser.NAMESPACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(PlantUMLGrammerParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(PlantUMLGrammerParser.SPACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Namespace_nameContext namespace_name() {
			return GetRuleContext<Namespace_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AQOLADBAZ() { return GetToken(PlantUMLGrammerParser.AQOLADBAZ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AQOLADBASTE() { return GetToken(PlantUMLGrammerParser.AQOLADBASTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_definitionContext[] type_definition() {
			return GetRuleContexts<Type_definitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_definitionContext type_definition(int i) {
			return GetRuleContext<Type_definitionContext>(i);
		}
		public Namespace_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterNamespace_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitNamespace_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespace_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Namespace_defContext namespace_def() {
		Namespace_defContext _localctx = new Namespace_defContext(Context, State);
		EnterRule(_localctx, 2, RULE_namespace_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			Match(NAMESPACE);
			State = 84;
			Match(SPACE);
			State = 85;
			namespace_name();
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPACE) {
				{
				State = 86;
				Match(SPACE);
				}
			}

			State = 89;
			Match(AQOLADBAZ);
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 825432735776L) != 0) {
				{
				{
				State = 90;
				type_definition();
				}
				}
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 96;
			Match(AQOLADBASTE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Note_exprContext note_expr() {
			return GetRuleContext<Note_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Namespace_defContext namespace_def() {
			return GetRuleContext<Namespace_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enum_defContext enum_def() {
			return GetRuleContext<Enum_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_defContext class_def() {
			return GetRuleContext<Class_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExtrafieldContext extrafield() {
			return GetRuleContext<ExtrafieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationContext relation() {
			return GetRuleContext<RelationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Singleline_commentContext singleline_comment() {
			return GetRuleContext<Singleline_commentContext>(0);
		}
		public Type_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterType_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitType_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_definition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_definitionContext type_definition() {
		Type_definitionContext _localctx = new Type_definitionContext(Context, State);
		EnterRule(_localctx, 4, RULE_type_definition);
		try {
			State = 105;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 98;
				note_expr();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 99;
				namespace_def();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 100;
				enum_def();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 101;
				class_def();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 102;
				extrafield();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 103;
				relation();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 104;
				singleline_comment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enum_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENUM() { return GetToken(PlantUMLGrammerParser.ENUM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(PlantUMLGrammerParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(PlantUMLGrammerParser.SPACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enum_nameContext enum_name() {
			return GetRuleContext<Enum_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Streotype_defContext streotype_def() {
			return GetRuleContext<Streotype_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ColorContext color() {
			return GetRuleContext<ColorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Field_def_blockContext field_def_block() {
			return GetRuleContext<Field_def_blockContext>(0);
		}
		public Enum_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enum_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterEnum_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitEnum_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnum_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Enum_defContext enum_def() {
		Enum_defContext _localctx = new Enum_defContext(Context, State);
		EnterRule(_localctx, 6, RULE_enum_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 107;
			Match(ENUM);
			State = 108;
			Match(SPACE);
			State = 109;
			enum_name();
			State = 111;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				{
				State = 110;
				Match(SPACE);
				}
				break;
			}
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 113;
				streotype_def();
				}
			}

			State = 118;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				{
				State = 116;
				Match(SPACE);
				State = 117;
				color();
				}
				break;
			}
			State = 121;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==AQOLADBAZ) {
				{
				State = 120;
				field_def_block();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Field_def_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AQOLADBAZ() { return GetToken(PlantUMLGrammerParser.AQOLADBAZ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AQOLADBASTE() { return GetToken(PlantUMLGrammerParser.AQOLADBASTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Field_defContext[] field_def() {
			return GetRuleContexts<Field_defContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Field_defContext field_def(int i) {
			return GetRuleContext<Field_defContext>(i);
		}
		public Field_def_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field_def_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterField_def_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitField_def_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField_def_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Field_def_blockContext field_def_block() {
		Field_def_blockContext _localctx = new Field_def_blockContext(Context, State);
		EnterRule(_localctx, 8, RULE_field_def_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			Match(AQOLADBAZ);
			State = 127;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 550296617030L) != 0) {
				{
				{
				State = 124;
				field_def();
				}
				}
				State = 129;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 130;
			Match(AQOLADBASTE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Field_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldNameContext fieldName() {
			return GetRuleContext<FieldNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Method_fieldContext method_field() {
			return GetRuleContext<Method_fieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AccessorContext accessor() {
			return GetRuleContext<AccessorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FieldTypeContext fieldType() {
			return GetRuleContext<FieldTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(PlantUMLGrammerParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(PlantUMLGrammerParser.SPACE, i);
		}
		public Field_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterField_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitField_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Field_defContext field_def() {
		Field_defContext _localctx = new Field_defContext(Context, State);
		EnterRule(_localctx, 10, RULE_field_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0 || _la==T__1) {
				{
				State = 132;
				method_field();
				}
			}

			State = 142;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (((_la) & ~0x3f) == 0 && ((1L << _la) & 1835072L) != 0) {
				{
				State = 135;
				accessor();
				State = 137;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SPACE) {
					{
					State = 136;
					Match(SPACE);
					}
				}

				State = 139;
				fieldType();
				State = 140;
				Match(SPACE);
				}
			}

			State = 144;
			fieldName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Method_fieldContext : ParserRuleContext {
		public Method_fieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method_field; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterMethod_field(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitMethod_field(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethod_field(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Method_fieldContext method_field() {
		Method_fieldContext _localctx = new Method_fieldContext(Context, State);
		EnterRule(_localctx, 12, RULE_method_field);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			_la = TokenStream.LA(1);
			if ( !(_la==T__0 || _la==T__1) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(PlantUMLGrammerParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(PlantUMLGrammerParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(PlantUMLGrammerParser.SPACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_nameContext class_name() {
			return GetRuleContext<Class_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Streotype_defContext streotype_def() {
			return GetRuleContext<Streotype_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ColorContext color() {
			return GetRuleContext<ColorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Field_def_blockContext field_def_block() {
			return GetRuleContext<Field_def_blockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Abstractclass_defContext abstractclass_def() {
			return GetRuleContext<Abstractclass_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Interface_defContext interface_def() {
			return GetRuleContext<Interface_defContext>(0);
		}
		public Class_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterClass_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitClass_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClass_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Class_defContext class_def() {
		Class_defContext _localctx = new Class_defContext(Context, State);
		EnterRule(_localctx, 14, RULE_class_def);
		int _la;
		try {
			State = 166;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case CLASS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 148;
				Match(CLASS);
				State = 149;
				Match(SPACE);
				State = 150;
				class_name();
				State = 152;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
				case 1:
					{
					State = 151;
					Match(SPACE);
					}
					break;
				}
				State = 155;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__2) {
					{
					State = 154;
					streotype_def();
					}
				}

				State = 159;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
				case 1:
					{
					State = 157;
					Match(SPACE);
					State = 158;
					color();
					}
					break;
				}
				State = 162;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AQOLADBAZ) {
					{
					State = 161;
					field_def_block();
					}
				}

				}
				break;
			case ABSTRACT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 164;
				abstractclass_def();
				}
				break;
			case INTERFACE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 165;
				interface_def();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Streotype_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StreotypenameContext streotypename() {
			return GetRuleContext<StreotypenameContext>(0);
		}
		public Streotype_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_streotype_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterStreotype_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitStreotype_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStreotype_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Streotype_defContext streotype_def() {
		Streotype_defContext _localctx = new Streotype_defContext(Context, State);
		EnterRule(_localctx, 16, RULE_streotype_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168;
			Match(T__2);
			State = 169;
			streotypename();
			State = 170;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StreotypenameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public StreotypenameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_streotypename; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterStreotypename(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitStreotypename(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStreotypename(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StreotypenameContext streotypename() {
		StreotypenameContext _localctx = new StreotypenameContext(Context, State);
		EnterRule(_localctx, 18, RULE_streotypename);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 172;
			identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Singleline_commentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Rest_of_lineContext rest_of_line() {
			return GetRuleContext<Rest_of_lineContext>(0);
		}
		public Singleline_commentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_singleline_comment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterSingleline_comment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitSingleline_comment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSingleline_comment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Singleline_commentContext singleline_comment() {
		Singleline_commentContext _localctx = new Singleline_commentContext(Context, State);
		EnterRule(_localctx, 20, RULE_singleline_comment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 174;
			Match(T__4);
			State = 175;
			rest_of_line();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rest_of_lineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NewLine() { return GetTokens(PlantUMLGrammerParser.NewLine); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NewLine(int i) {
			return GetToken(PlantUMLGrammerParser.NewLine, i);
		}
		public Rest_of_lineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rest_of_line; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterRest_of_line(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitRest_of_line(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRest_of_line(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Rest_of_lineContext rest_of_line() {
		Rest_of_lineContext _localctx = new Rest_of_lineContext(Context, State);
		EnterRule(_localctx, 22, RULE_rest_of_line);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 180;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 177;
					_la = TokenStream.LA(1);
					if ( _la <= 0 || (_la==NewLine) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					} 
				}
				State = 182;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Abstractclass_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ABSTRACT() { return GetToken(PlantUMLGrammerParser.ABSTRACT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(PlantUMLGrammerParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(PlantUMLGrammerParser.SPACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(PlantUMLGrammerParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Class_nameContext class_name() {
			return GetRuleContext<Class_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Streotype_defContext streotype_def() {
			return GetRuleContext<Streotype_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ColorContext color() {
			return GetRuleContext<ColorContext>(0);
		}
		public Abstractclass_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_abstractclass_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterAbstractclass_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitAbstractclass_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAbstractclass_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Abstractclass_defContext abstractclass_def() {
		Abstractclass_defContext _localctx = new Abstractclass_defContext(Context, State);
		EnterRule(_localctx, 24, RULE_abstractclass_def);
		int _la;
		try {
			State = 213;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 183;
				Match(ABSTRACT);
				State = 184;
				Match(SPACE);
				State = 185;
				Match(CLASS);
				State = 186;
				Match(SPACE);
				State = 187;
				class_name();
				State = 189;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
				case 1:
					{
					State = 188;
					Match(SPACE);
					}
					break;
				}
				State = 192;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__2) {
					{
					State = 191;
					streotype_def();
					}
				}

				State = 194;
				Match(SPACE);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 196;
				Match(ABSTRACT);
				State = 197;
				Match(SPACE);
				State = 198;
				class_name();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 199;
				Match(ABSTRACT);
				State = 200;
				Match(SPACE);
				State = 201;
				class_name();
				State = 203;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
				case 1:
					{
					State = 202;
					Match(SPACE);
					}
					break;
				}
				State = 206;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__2) {
					{
					State = 205;
					streotype_def();
					}
				}

				State = 208;
				Match(SPACE);
				State = 211;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__5) {
					{
					State = 209;
					Match(T__5);
					State = 210;
					color();
					}
				}

				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Interface_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTERFACE() { return GetToken(PlantUMLGrammerParser.INTERFACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE() { return GetToken(PlantUMLGrammerParser.SPACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Interface_nameContext interface_name() {
			return GetRuleContext<Interface_nameContext>(0);
		}
		public Interface_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interface_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterInterface_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitInterface_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterface_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Interface_defContext interface_def() {
		Interface_defContext _localctx = new Interface_defContext(Context, State);
		EnterRule(_localctx, 26, RULE_interface_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 215;
			Match(INTERFACE);
			State = 216;
			Match(SPACE);
			State = 217;
			interface_name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ColorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Color() { return GetToken(PlantUMLGrammerParser.Color, 0); }
		public ColorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_color; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterColor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitColor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ColorContext color() {
		ColorContext _localctx = new ColorContext(Context, State);
		EnterRule(_localctx, 28, RULE_color);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 219;
			Match(Color);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExtrafieldContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OwnerClassContext ownerClass() {
			return GetRuleContext<OwnerClassContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(PlantUMLGrammerParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(PlantUMLGrammerParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(PlantUMLGrammerParser.SPACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AccessorContext accessor() {
			return GetRuleContext<AccessorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FieldTypeContext fieldType() {
			return GetRuleContext<FieldTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FieldNameContext fieldName() {
			return GetRuleContext<FieldNameContext>(0);
		}
		public ExtrafieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_extrafield; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterExtrafield(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitExtrafield(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExtrafield(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExtrafieldContext extrafield() {
		ExtrafieldContext _localctx = new ExtrafieldContext(Context, State);
		EnterRule(_localctx, 30, RULE_extrafield);
		int _la;
		try {
			State = 257;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 221;
				ownerClass();
				State = 223;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SPACE) {
					{
					State = 222;
					Match(SPACE);
					}
				}

				State = 225;
				Match(COLON);
				State = 226;
				Match(SPACE);
				State = 227;
				accessor();
				State = 229;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SPACE) {
					{
					State = 228;
					Match(SPACE);
					}
				}

				State = 231;
				fieldType();
				State = 232;
				Match(SPACE);
				State = 233;
				fieldName();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 235;
				ownerClass();
				State = 237;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SPACE) {
					{
					State = 236;
					Match(SPACE);
					}
				}

				State = 239;
				Match(COLON);
				State = 240;
				Match(SPACE);
				State = 241;
				accessor();
				State = 243;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SPACE) {
					{
					State = 242;
					Match(SPACE);
					}
				}

				State = 245;
				fieldType();
				State = 246;
				Match(SPACE);
				State = 247;
				fieldName();
				State = 249;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SPACE) {
					{
					State = 248;
					Match(SPACE);
					}
				}

				State = 251;
				Match(T__6);
				State = 253;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==SPACE) {
					{
					State = 252;
					Match(SPACE);
					}
				}

				State = 255;
				Match(T__7);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FromContext from() {
			return GetRuleContext<FromContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(PlantUMLGrammerParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(PlantUMLGrammerParser.SPACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationTypeContext relationType() {
			return GetRuleContext<RelationTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ToContext to() {
			return GetRuleContext<ToContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(PlantUMLGrammerParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LinktextContext linktext() {
			return GetRuleContext<LinktextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DirectionContext[] direction() {
			return GetRuleContexts<DirectionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DirectionContext direction(int i) {
			return GetRuleContext<DirectionContext>(i);
		}
		public RelationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterRelation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitRelation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationContext relation() {
		RelationContext _localctx = new RelationContext(Context, State);
		EnterRule(_localctx, 32, RULE_relation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 259;
			from();
			State = 260;
			Match(SPACE);
			State = 261;
			relationType();
			State = 262;
			Match(SPACE);
			State = 263;
			to();
			State = 278;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 264;
				Match(COLON);
				State = 266;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,32,Context) ) {
				case 1:
					{
					State = 265;
					direction();
					}
					break;
				}
				State = 269;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,33,Context) ) {
				case 1:
					{
					State = 268;
					Match(SPACE);
					}
					break;
				}
				State = 271;
				linktext();
				State = 273;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,34,Context) ) {
				case 1:
					{
					State = 272;
					Match(SPACE);
					}
					break;
				}
				State = 276;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__8 || _la==T__9) {
					{
					State = 275;
					direction();
					}
				}

				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectionContext : ParserRuleContext {
		public DirectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_direction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterDirection(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitDirection(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDirection(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DirectionContext direction() {
		DirectionContext _localctx = new DirectionContext(Context, State);
		EnterRule(_localctx, 34, RULE_direction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 280;
			_la = TokenStream.LA(1);
			if ( !(_la==T__8 || _la==T__9) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FromContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public FromContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_from; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterFrom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitFrom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFrom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FromContext from() {
		FromContext _localctx = new FromContext(Context, State);
		EnterRule(_localctx, 36, RULE_from);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 282;
			identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ToContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ToContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_to; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterTo(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitTo(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTo(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ToContext to() {
		ToContext _localctx = new ToContext(Context, State);
		EnterRule(_localctx, 38, RULE_to);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 284;
			identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Interface_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(PlantUMLGrammerParser.Identifier, 0); }
		public Interface_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interface_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterInterface_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitInterface_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterface_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Interface_nameContext interface_name() {
		Interface_nameContext _localctx = new Interface_nameContext(Context, State);
		EnterRule(_localctx, 40, RULE_interface_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 286;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LinktextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SomethingsContext somethings() {
			return GetRuleContext<SomethingsContext>(0);
		}
		public LinktextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_linktext; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterLinktext(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitLinktext(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLinktext(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LinktextContext linktext() {
		LinktextContext _localctx = new LinktextContext(Context, State);
		EnterRule(_localctx, 42, RULE_linktext);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 288;
			somethings();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationTypeContext : ParserRuleContext {
		public RelationTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterRelationType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitRelationType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationTypeContext relationType() {
		RelationTypeContext _localctx = new RelationTypeContext(Context, State);
		EnterRule(_localctx, 44, RULE_relationType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 290;
			_la = TokenStream.LA(1);
			if ( !(((_la) & ~0x3f) == 0 && ((1L << _la) & 522240L) != 0) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AccessorContext : ParserRuleContext {
		public AccessorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_accessor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterAccessor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitAccessor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAccessor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AccessorContext accessor() {
		AccessorContext _localctx = new AccessorContext(Context, State);
		EnterRule(_localctx, 46, RULE_accessor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 292;
			_la = TokenStream.LA(1);
			if ( !(((_la) & ~0x3f) == 0 && ((1L << _la) & 1835072L) != 0) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public FieldNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterFieldName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitFieldName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldNameContext fieldName() {
		FieldNameContext _localctx = new FieldNameContext(Context, State);
		EnterRule(_localctx, 48, RULE_fieldName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 294;
			identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OwnerClassContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public OwnerClassContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ownerClass; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterOwnerClass(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitOwnerClass(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOwnerClass(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OwnerClassContext ownerClass() {
		OwnerClassContext _localctx = new OwnerClassContext(Context, State);
		EnterRule(_localctx, 50, RULE_ownerClass);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 296;
			identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public FieldTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterFieldType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitFieldType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldTypeContext fieldType() {
		FieldTypeContext _localctx = new FieldTypeContext(Context, State);
		EnterRule(_localctx, 52, RULE_fieldType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 298;
			identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(PlantUMLGrammerParser.Identifier, 0); }
		public Class_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterClass_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitClass_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClass_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Class_nameContext class_name() {
		Class_nameContext _localctx = new Class_nameContext(Context, State);
		EnterRule(_localctx, 54, RULE_class_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 300;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enum_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(PlantUMLGrammerParser.Identifier, 0); }
		public Enum_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enum_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterEnum_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitEnum_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnum_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Enum_nameContext enum_name() {
		Enum_nameContext _localctx = new Enum_nameContext(Context, State);
		EnterRule(_localctx, 56, RULE_enum_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 302;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Namespace_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DotIdentifierContext dotIdentifier() {
			return GetRuleContext<DotIdentifierContext>(0);
		}
		public Namespace_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterNamespace_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitNamespace_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespace_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Namespace_nameContext namespace_name() {
		Namespace_nameContext _localctx = new Namespace_nameContext(Context, State);
		EnterRule(_localctx, 58, RULE_namespace_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 304;
			dotIdentifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(PlantUMLGrammerParser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(PlantUMLGrammerParser.STRING, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 60, RULE_identifier);
		try {
			State = 311;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Identifier:
				EnterOuterAlt(_localctx, 1);
				{
				State = 306;
				Match(Identifier);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 2);
				{
				State = 307;
				Match(T__20);
				State = 308;
				Match(Identifier);
				State = 309;
				Match(T__20);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 3);
				{
				State = 310;
				Match(STRING);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DotIdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DotIdentifierContext dotIdentifier() {
			return GetRuleContext<DotIdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(PlantUMLGrammerParser.STRING, 0); }
		public DotIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dotIdentifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterDotIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitDotIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDotIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DotIdentifierContext dotIdentifier() {
		DotIdentifierContext _localctx = new DotIdentifierContext(Context, State);
		EnterRule(_localctx, 62, RULE_dotIdentifier);
		try {
			State = 319;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,38,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 313;
				identifier();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 314;
				identifier();
				State = 315;
				Match(T__21);
				State = 316;
				dotIdentifier();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 318;
				Match(STRING);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Note_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTE() { return GetToken(PlantUMLGrammerParser.NOTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE() { return GetToken(PlantUMLGrammerParser.SPACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SomethingsToEndNoteContext somethingsToEndNote() {
			return GetRuleContext<SomethingsToEndNoteContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDNOTE() { return GetToken(PlantUMLGrammerParser.ENDNOTE, 0); }
		public Note_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_note_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterNote_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitNote_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNote_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Note_exprContext note_expr() {
		Note_exprContext _localctx = new Note_exprContext(Context, State);
		EnterRule(_localctx, 64, RULE_note_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 321;
			Match(NOTE);
			State = 322;
			Match(SPACE);
			State = 323;
			somethingsToEndNote();
			State = 324;
			Match(ENDNOTE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SomethingsToEndNoteContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ENDNOTE() { return GetTokens(PlantUMLGrammerParser.ENDNOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDNOTE(int i) {
			return GetToken(PlantUMLGrammerParser.ENDNOTE, i);
		}
		public SomethingsToEndNoteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_somethingsToEndNote; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterSomethingsToEndNote(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitSomethingsToEndNote(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSomethingsToEndNote(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SomethingsToEndNoteContext somethingsToEndNote() {
		SomethingsToEndNoteContext _localctx = new SomethingsToEndNoteContext(Context, State);
		EnterRule(_localctx, 66, RULE_somethingsToEndNote);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 329;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 7696581394430L) != 0) {
				{
				{
				State = 326;
				_la = TokenStream.LA(1);
				if ( _la <= 0 || (_la==ENDNOTE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 331;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SomethingsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Unicode() { return GetTokens(PlantUMLGrammerParser.Unicode); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Unicode(int i) {
			return GetToken(PlantUMLGrammerParser.Unicode, i);
		}
		public SomethingsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_somethings; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.EnterSomethings(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IPlantUMLGrammerListener typedListener = listener as IPlantUMLGrammerListener;
			if (typedListener != null) typedListener.ExitSomethings(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlantUMLGrammerVisitor<TResult> typedVisitor = visitor as IPlantUMLGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSomethings(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SomethingsContext somethings() {
		SomethingsContext _localctx = new SomethingsContext(Context, State);
		EnterRule(_localctx, 68, RULE_somethings);
		int _la;
		try {
			int _alt;
			State = 344;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,42,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 335;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,40,Context);
				while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1+1 ) {
						{
						{
						State = 332;
						MatchWildcard();
						}
						} 
					}
					State = 337;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,40,Context);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 341;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Unicode) {
					{
					{
					State = 338;
					Match(Unicode);
					}
					}
					State = 343;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,42,347,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,1,0,1,0,5,
		0,73,8,0,10,0,12,0,76,9,0,1,0,3,0,79,8,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,3,
		1,88,8,1,1,1,1,1,5,1,92,8,1,10,1,12,1,95,9,1,1,1,1,1,1,2,1,2,1,2,1,2,1,
		2,1,2,1,2,3,2,106,8,2,1,3,1,3,1,3,1,3,3,3,112,8,3,1,3,3,3,115,8,3,1,3,
		1,3,3,3,119,8,3,1,3,3,3,122,8,3,1,4,1,4,5,4,126,8,4,10,4,12,4,129,9,4,
		1,4,1,4,1,5,3,5,134,8,5,1,5,1,5,3,5,138,8,5,1,5,1,5,1,5,3,5,143,8,5,1,
		5,1,5,1,6,1,6,1,7,1,7,1,7,1,7,3,7,153,8,7,1,7,3,7,156,8,7,1,7,1,7,3,7,
		160,8,7,1,7,3,7,163,8,7,1,7,1,7,3,7,167,8,7,1,8,1,8,1,8,1,8,1,9,1,9,1,
		10,1,10,1,10,1,11,5,11,179,8,11,10,11,12,11,182,9,11,1,12,1,12,1,12,1,
		12,1,12,1,12,3,12,190,8,12,1,12,3,12,193,8,12,1,12,1,12,1,12,1,12,1,12,
		1,12,1,12,1,12,1,12,3,12,204,8,12,1,12,3,12,207,8,12,1,12,1,12,1,12,3,
		12,212,8,12,3,12,214,8,12,1,13,1,13,1,13,1,13,1,14,1,14,1,15,1,15,3,15,
		224,8,15,1,15,1,15,1,15,1,15,3,15,230,8,15,1,15,1,15,1,15,1,15,1,15,1,
		15,3,15,238,8,15,1,15,1,15,1,15,1,15,3,15,244,8,15,1,15,1,15,1,15,1,15,
		3,15,250,8,15,1,15,1,15,3,15,254,8,15,1,15,1,15,3,15,258,8,15,1,16,1,16,
		1,16,1,16,1,16,1,16,1,16,3,16,267,8,16,1,16,3,16,270,8,16,1,16,1,16,3,
		16,274,8,16,1,16,3,16,277,8,16,3,16,279,8,16,1,17,1,17,1,18,1,18,1,19,
		1,19,1,20,1,20,1,21,1,21,1,22,1,22,1,23,1,23,1,24,1,24,1,25,1,25,1,26,
		1,26,1,27,1,27,1,28,1,28,1,29,1,29,1,30,1,30,1,30,1,30,1,30,3,30,312,8,
		30,1,31,1,31,1,31,1,31,1,31,1,31,3,31,320,8,31,1,32,1,32,1,32,1,32,1,32,
		1,33,5,33,328,8,33,10,33,12,33,331,9,33,1,34,5,34,334,8,34,10,34,12,34,
		337,9,34,1,34,5,34,340,8,34,10,34,12,34,343,9,34,3,34,345,8,34,1,34,1,
		335,0,35,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,
		44,46,48,50,52,54,56,58,60,62,64,66,68,0,6,1,0,1,2,1,0,37,37,1,0,9,10,
		1,0,11,18,2,0,6,6,18,20,1,0,40,40,363,0,70,1,0,0,0,2,83,1,0,0,0,4,105,
		1,0,0,0,6,107,1,0,0,0,8,123,1,0,0,0,10,133,1,0,0,0,12,146,1,0,0,0,14,166,
		1,0,0,0,16,168,1,0,0,0,18,172,1,0,0,0,20,174,1,0,0,0,22,180,1,0,0,0,24,
		213,1,0,0,0,26,215,1,0,0,0,28,219,1,0,0,0,30,257,1,0,0,0,32,259,1,0,0,
		0,34,280,1,0,0,0,36,282,1,0,0,0,38,284,1,0,0,0,40,286,1,0,0,0,42,288,1,
		0,0,0,44,290,1,0,0,0,46,292,1,0,0,0,48,294,1,0,0,0,50,296,1,0,0,0,52,298,
		1,0,0,0,54,300,1,0,0,0,56,302,1,0,0,0,58,304,1,0,0,0,60,311,1,0,0,0,62,
		319,1,0,0,0,64,321,1,0,0,0,66,329,1,0,0,0,68,344,1,0,0,0,70,74,5,32,0,
		0,71,73,3,4,2,0,72,71,1,0,0,0,73,76,1,0,0,0,74,72,1,0,0,0,74,75,1,0,0,
		0,75,78,1,0,0,0,76,74,1,0,0,0,77,79,5,36,0,0,78,77,1,0,0,0,78,79,1,0,0,
		0,79,80,1,0,0,0,80,81,5,33,0,0,81,82,5,0,0,1,82,1,1,0,0,0,83,84,5,23,0,
		0,84,85,5,36,0,0,85,87,3,58,29,0,86,88,5,36,0,0,87,86,1,0,0,0,87,88,1,
		0,0,0,88,89,1,0,0,0,89,93,5,34,0,0,90,92,3,4,2,0,91,90,1,0,0,0,92,95,1,
		0,0,0,93,91,1,0,0,0,93,94,1,0,0,0,94,96,1,0,0,0,95,93,1,0,0,0,96,97,5,
		35,0,0,97,3,1,0,0,0,98,106,3,64,32,0,99,106,3,2,1,0,100,106,3,6,3,0,101,
		106,3,14,7,0,102,106,3,30,15,0,103,106,3,32,16,0,104,106,3,20,10,0,105,
		98,1,0,0,0,105,99,1,0,0,0,105,100,1,0,0,0,105,101,1,0,0,0,105,102,1,0,
		0,0,105,103,1,0,0,0,105,104,1,0,0,0,106,5,1,0,0,0,107,108,5,25,0,0,108,
		109,5,36,0,0,109,111,3,56,28,0,110,112,5,36,0,0,111,110,1,0,0,0,111,112,
		1,0,0,0,112,114,1,0,0,0,113,115,3,16,8,0,114,113,1,0,0,0,114,115,1,0,0,
		0,115,118,1,0,0,0,116,117,5,36,0,0,117,119,3,28,14,0,118,116,1,0,0,0,118,
		119,1,0,0,0,119,121,1,0,0,0,120,122,3,8,4,0,121,120,1,0,0,0,121,122,1,
		0,0,0,122,7,1,0,0,0,123,127,5,34,0,0,124,126,3,10,5,0,125,124,1,0,0,0,
		126,129,1,0,0,0,127,125,1,0,0,0,127,128,1,0,0,0,128,130,1,0,0,0,129,127,
		1,0,0,0,130,131,5,35,0,0,131,9,1,0,0,0,132,134,3,12,6,0,133,132,1,0,0,
		0,133,134,1,0,0,0,134,142,1,0,0,0,135,137,3,46,23,0,136,138,5,36,0,0,137,
		136,1,0,0,0,137,138,1,0,0,0,138,139,1,0,0,0,139,140,3,52,26,0,140,141,
		5,36,0,0,141,143,1,0,0,0,142,135,1,0,0,0,142,143,1,0,0,0,143,144,1,0,0,
		0,144,145,3,48,24,0,145,11,1,0,0,0,146,147,7,0,0,0,147,13,1,0,0,0,148,
		149,5,24,0,0,149,150,5,36,0,0,150,152,3,54,27,0,151,153,5,36,0,0,152,151,
		1,0,0,0,152,153,1,0,0,0,153,155,1,0,0,0,154,156,3,16,8,0,155,154,1,0,0,
		0,155,156,1,0,0,0,156,159,1,0,0,0,157,158,5,36,0,0,158,160,3,28,14,0,159,
		157,1,0,0,0,159,160,1,0,0,0,160,162,1,0,0,0,161,163,3,8,4,0,162,161,1,
		0,0,0,162,163,1,0,0,0,163,167,1,0,0,0,164,167,3,24,12,0,165,167,3,26,13,
		0,166,148,1,0,0,0,166,164,1,0,0,0,166,165,1,0,0,0,167,15,1,0,0,0,168,169,
		5,3,0,0,169,170,3,18,9,0,170,171,5,4,0,0,171,17,1,0,0,0,172,173,3,60,30,
		0,173,19,1,0,0,0,174,175,5,5,0,0,175,176,3,22,11,0,176,21,1,0,0,0,177,
		179,8,1,0,0,178,177,1,0,0,0,179,182,1,0,0,0,180,178,1,0,0,0,180,181,1,
		0,0,0,181,23,1,0,0,0,182,180,1,0,0,0,183,184,5,26,0,0,184,185,5,36,0,0,
		185,186,5,24,0,0,186,187,5,36,0,0,187,189,3,54,27,0,188,190,5,36,0,0,189,
		188,1,0,0,0,189,190,1,0,0,0,190,192,1,0,0,0,191,193,3,16,8,0,192,191,1,
		0,0,0,192,193,1,0,0,0,193,194,1,0,0,0,194,195,5,36,0,0,195,214,1,0,0,0,
		196,197,5,26,0,0,197,198,5,36,0,0,198,214,3,54,27,0,199,200,5,26,0,0,200,
		201,5,36,0,0,201,203,3,54,27,0,202,204,5,36,0,0,203,202,1,0,0,0,203,204,
		1,0,0,0,204,206,1,0,0,0,205,207,3,16,8,0,206,205,1,0,0,0,206,207,1,0,0,
		0,207,208,1,0,0,0,208,211,5,36,0,0,209,210,5,6,0,0,210,212,3,28,14,0,211,
		209,1,0,0,0,211,212,1,0,0,0,212,214,1,0,0,0,213,183,1,0,0,0,213,196,1,
		0,0,0,213,199,1,0,0,0,214,25,1,0,0,0,215,216,5,27,0,0,216,217,5,36,0,0,
		217,218,3,40,20,0,218,27,1,0,0,0,219,220,5,42,0,0,220,29,1,0,0,0,221,223,
		3,50,25,0,222,224,5,36,0,0,223,222,1,0,0,0,223,224,1,0,0,0,224,225,1,0,
		0,0,225,226,5,28,0,0,226,227,5,36,0,0,227,229,3,46,23,0,228,230,5,36,0,
		0,229,228,1,0,0,0,229,230,1,0,0,0,230,231,1,0,0,0,231,232,3,52,26,0,232,
		233,5,36,0,0,233,234,3,48,24,0,234,258,1,0,0,0,235,237,3,50,25,0,236,238,
		5,36,0,0,237,236,1,0,0,0,237,238,1,0,0,0,238,239,1,0,0,0,239,240,5,28,
		0,0,240,241,5,36,0,0,241,243,3,46,23,0,242,244,5,36,0,0,243,242,1,0,0,
		0,243,244,1,0,0,0,244,245,1,0,0,0,245,246,3,52,26,0,246,247,5,36,0,0,247,
		249,3,48,24,0,248,250,5,36,0,0,249,248,1,0,0,0,249,250,1,0,0,0,250,251,
		1,0,0,0,251,253,5,7,0,0,252,254,5,36,0,0,253,252,1,0,0,0,253,254,1,0,0,
		0,254,255,1,0,0,0,255,256,5,8,0,0,256,258,1,0,0,0,257,221,1,0,0,0,257,
		235,1,0,0,0,258,31,1,0,0,0,259,260,3,36,18,0,260,261,5,36,0,0,261,262,
		3,44,22,0,262,263,5,36,0,0,263,278,3,38,19,0,264,266,5,28,0,0,265,267,
		3,34,17,0,266,265,1,0,0,0,266,267,1,0,0,0,267,269,1,0,0,0,268,270,5,36,
		0,0,269,268,1,0,0,0,269,270,1,0,0,0,270,271,1,0,0,0,271,273,3,42,21,0,
		272,274,5,36,0,0,273,272,1,0,0,0,273,274,1,0,0,0,274,276,1,0,0,0,275,277,
		3,34,17,0,276,275,1,0,0,0,276,277,1,0,0,0,277,279,1,0,0,0,278,264,1,0,
		0,0,278,279,1,0,0,0,279,33,1,0,0,0,280,281,7,2,0,0,281,35,1,0,0,0,282,
		283,3,60,30,0,283,37,1,0,0,0,284,285,3,60,30,0,285,39,1,0,0,0,286,287,
		5,39,0,0,287,41,1,0,0,0,288,289,3,68,34,0,289,43,1,0,0,0,290,291,7,3,0,
		0,291,45,1,0,0,0,292,293,7,4,0,0,293,47,1,0,0,0,294,295,3,60,30,0,295,
		49,1,0,0,0,296,297,3,60,30,0,297,51,1,0,0,0,298,299,3,60,30,0,299,53,1,
		0,0,0,300,301,5,39,0,0,301,55,1,0,0,0,302,303,5,39,0,0,303,57,1,0,0,0,
		304,305,3,62,31,0,305,59,1,0,0,0,306,312,5,39,0,0,307,308,5,21,0,0,308,
		309,5,39,0,0,309,312,5,21,0,0,310,312,5,29,0,0,311,306,1,0,0,0,311,307,
		1,0,0,0,311,310,1,0,0,0,312,61,1,0,0,0,313,320,3,60,30,0,314,315,3,60,
		30,0,315,316,5,22,0,0,316,317,3,62,31,0,317,320,1,0,0,0,318,320,5,29,0,
		0,319,313,1,0,0,0,319,314,1,0,0,0,319,318,1,0,0,0,320,63,1,0,0,0,321,322,
		5,38,0,0,322,323,5,36,0,0,323,324,3,66,33,0,324,325,5,40,0,0,325,65,1,
		0,0,0,326,328,8,5,0,0,327,326,1,0,0,0,328,331,1,0,0,0,329,327,1,0,0,0,
		329,330,1,0,0,0,330,67,1,0,0,0,331,329,1,0,0,0,332,334,9,0,0,0,333,332,
		1,0,0,0,334,337,1,0,0,0,335,336,1,0,0,0,335,333,1,0,0,0,336,345,1,0,0,
		0,337,335,1,0,0,0,338,340,5,41,0,0,339,338,1,0,0,0,340,343,1,0,0,0,341,
		339,1,0,0,0,341,342,1,0,0,0,342,345,1,0,0,0,343,341,1,0,0,0,344,335,1,
		0,0,0,344,341,1,0,0,0,345,69,1,0,0,0,43,74,78,87,93,105,111,114,118,121,
		127,133,137,142,152,155,159,162,166,180,189,192,203,206,211,213,223,229,
		237,243,249,253,257,266,269,273,276,278,311,319,329,335,341,344
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
