//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PlantUMLGrammer.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PlantUMLGrammerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IPlantUMLGrammerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] PlantUMLGrammerParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.namespace_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_def([NotNull] PlantUMLGrammerParser.Namespace_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_definition([NotNull] PlantUMLGrammerParser.Type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.enum_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_def([NotNull] PlantUMLGrammerParser.Enum_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.field_def_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_def_block([NotNull] PlantUMLGrammerParser.Field_def_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.field_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_def([NotNull] PlantUMLGrammerParser.Field_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.method_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_field([NotNull] PlantUMLGrammerParser.Method_fieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.class_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_def([NotNull] PlantUMLGrammerParser.Class_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.streotype_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStreotype_def([NotNull] PlantUMLGrammerParser.Streotype_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.streotypename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStreotypename([NotNull] PlantUMLGrammerParser.StreotypenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.singleline_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleline_comment([NotNull] PlantUMLGrammerParser.Singleline_commentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.rest_of_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRest_of_line([NotNull] PlantUMLGrammerParser.Rest_of_lineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.abstractclass_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractclass_def([NotNull] PlantUMLGrammerParser.Abstractclass_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.interface_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_def([NotNull] PlantUMLGrammerParser.Interface_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColor([NotNull] PlantUMLGrammerParser.ColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.extrafield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtrafield([NotNull] PlantUMLGrammerParser.ExtrafieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelation([NotNull] PlantUMLGrammerParser.RelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirection([NotNull] PlantUMLGrammerParser.DirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom([NotNull] PlantUMLGrammerParser.FromContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.to"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTo([NotNull] PlantUMLGrammerParser.ToContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.interface_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_name([NotNull] PlantUMLGrammerParser.Interface_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.linktext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinktext([NotNull] PlantUMLGrammerParser.LinktextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.relationType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationType([NotNull] PlantUMLGrammerParser.RelationTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.accessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessor([NotNull] PlantUMLGrammerParser.AccessorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldName([NotNull] PlantUMLGrammerParser.FieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.ownerClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOwnerClass([NotNull] PlantUMLGrammerParser.OwnerClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.fieldType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldType([NotNull] PlantUMLGrammerParser.FieldTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_name([NotNull] PlantUMLGrammerParser.Class_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.enum_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_name([NotNull] PlantUMLGrammerParser.Enum_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.namespace_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_name([NotNull] PlantUMLGrammerParser.Namespace_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] PlantUMLGrammerParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.dotIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotIdentifier([NotNull] PlantUMLGrammerParser.DotIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.note_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNote_expr([NotNull] PlantUMLGrammerParser.Note_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.somethingsToEndNote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSomethingsToEndNote([NotNull] PlantUMLGrammerParser.SomethingsToEndNoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlantUMLGrammerParser.somethings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSomethings([NotNull] PlantUMLGrammerParser.SomethingsContext context);
}
